// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Локальное подключение к PostgreSQL из Docker
    url: "postgresql://moyaigra_user:moyaigra_password@localhost:5432/moyaigra_db?schema=public",
  },
});
